version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - >
        git_lfs_ver="3.6.1";
        wget -qO- https://github.com/git-lfs/git-lfs/releases/download/v${git_lfs_ver}/git-lfs-linux-amd64-v${git_lfs_ver}.tar.gz
        | tar -xOz git-lfs-${git_lfs_ver}/git-lfs > git-lfs
      - chmod u+x git-lfs
      - git config filter.lfs.process "`pwd`/git-lfs filter-process"
      - git config filter.lfs.smudge  "`pwd`/git-lfs smudge -- %f"
      - git config filter.lfs.clean "`pwd`/git-lfs clean -- %f"
      - ./git-lfs install
      - ./git-lfs fetch
      - ./git-lfs checkout
    post_create_environment:
        - pip install poetry
    post_install:
        - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install

sphinx:
  configuration: source/conf.py
