# Convert images
#
# Targets generated by this Makefile are committed to Git LFS. This is due to
# image conversion tools not being available in the readthedocs.org build
# environment.

image_dir = source/_static/images

targets := $(image_dir)/cc-by-4.0.pdf

.PHONY: all
all: $(targets)

$(image_dir)/cc-by-4.0.pdf : $(image_dir)/cc-by-4.0.eps
	ghostscript -dEPSCrop -sDEVICE=pdfwrite -o $@ $<

.PHONY : clean
clean :
	-rm $(targets)
