name: test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build HTML
        run: make html

      - name: Check spelling
        run: |
          sudo apt-get install enchant hunspell hunspell-en-gb
          make spelling SPHINXOPTS="-W"

      - name: Check links
        run: make linkcheck

      - name: Install Vale styles
        run: make install-vale-styles

      - name: Install Vale
        run: |
          curl --location https://github.com/errata-ai/vale/releases/download/v2.6.3/vale_2.6.3_Linux_64-bit.tar.gz --output vale.tar.gz
          mkdir "${GITHUB_WORKSPACE}/bin"
          tar xvfz vale.tar.gz --directory "${GITHUB_WORKSPACE}/bin" vale
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Lint prose
        run: |
          vale --version
          bash lint-prose.sh
